### PR TITLE
Update the README configuration with the scope GET parameter

### PR DESCRIPTION
**Pull request by MrPowers**
This should save some ppl from having to search the internet for the solution.

### CODE REVIEW

**Comment by joneslee85** [comment]
:+1:

**Comment by MrPowers** [comment]
Is this gem still being maintained?  The build is failing, but I just updated the README, so it's not my fault! :smiley:

**Comment by joneslee85** [comment]
@MrPowers yup, the build failed, I am not sure about the status of the gem, seems dormant

**Comment by jeremytregunna** [comment]
It's not really maintained, but should be. I've created #141 to address this.

**Pull request merged**
