### PR TITLE
New label colours

### PR DESCRIPTION
**Pull request by Anti-Fun**
As per issue #105 just added the new label colours that trello supports. 

Did not have to change spec for this....

### CODE REVIEW

**Comment by jeremytregunna** [comment]
Can you add test cases to cover this? I'll merge it in. My apologies for the delay in getting to this.

**Comment by Anti-Fun** [comment]
Existing labels context covers this? I can improve it if that's what you want?

https://github.com/jeremytregunna/ruby-trello/blob/master/spec/card_spec.rb#L253-L294

**Comment by Anti-Fun** [comment]
Ok. I've added the new test, so ignore my last comment I guess.

**Comment by jeremytregunna** [comment]
Thanks!

**Comment by jmburges** [comment]
this still doesn't account for the `board#label` method. I'll be submitting a pull-request in a sec with that change

**Pull request merged**
