### PR TITLE
allow to create a checklist with a card_id

### PR DESCRIPTION
**Pull request by verlinden**

### CODE REVIEW

**Comment by danmcp** [comment]
@verlinden +1 to the need for the change although you need to fix the corresponding tests.

FYI I just got this email from Trello on the subject:

I'm writing you because our systems indicate that you are one of a small number of developers using an API route that we are going to be deprecating on October 30th, 2015. You will need to update your integration for it to continue operating as expected.

We have updated our reference documentation here: https://developers.trello.com/advanced-reference/checklist

What is Changing?
Specifically, we are addressing a bug which allowed Checklists to become orphaned, and not associated with a card.

To address this, we are removing the ability to modify the idCard associated with a checklist, and making idCard required for all new checklist creation.

How Do I Fix This?
To keep your code functional, find the logic where you're creating a checklist and then adding it to a card. Instead of doing that, just include the idCard in the checklist creation. That should be it!

If you have any additional questions about this change, don't hesitate to let us know.

**Comment by danmcp** [comment]
Submitted https://github.com/jeremytregunna/ruby-trello/pull/161 with test fixes.

**Comment by joneslee85** [comment]
close this because I merged #161

**Comment by verlinden** [comment]
Thanks for the deprecation info.

**Pull request closed without merging**
